---
title: "mimic4"
output:
  html_document:
    toc: true
    toc_depth: 3
    theme: united
  pdf_document: 
    toc: true
    toc_depth: 3
  word_document:
    toc: true
    toc_depth: '3'
date: "`r Sys.Date()`"
editor_options:
  markdown:
    wrap: 72
---

# [**MIMIC4**]{.underline}

```{r read library, echo=F, warning=FALSE, message= FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r download import, echo=T, warning=F, message= F}
library(ricu) #install.packages("ricu")
library(fst)#install.packages("fst")
library(utils)
library(tidyverse)
library(units)
library(dplyr)
library(here)
library(gtsummary) #install.packages("gtsummary")
library(openxlsx)
Sys.setenv(RICU_DATA_PATH="C:\\Users\\aomura\\Desktop\\ricu2") #C:\\Users\\aomura\\OneDrive - Oregon Health & Science University\\Desktop\\ricu2
detach("package:ricu", unload = TRUE)
```

### MIMIC4 data
```{r m4 data read, include=F}
###Set folder path
Sys.setenv(RICU_DATA_PATH="C:\\Users\\aomura\\Desktop\\ricu2") 
dir5<-paste0(ricu::data_dir(),"\\miiv")
###Import mimic4 data <- already done
#ricu::import_src("miiv", data_dir=dir5, force=T, verbose=TRUE)
```

```{r M4 data trimming mimic4, include=F}
##### First, get subject_id who used penems using prescription.csv
#penem_names <- "penem|PENEM|primaxin|Primaxin|PRIMAXIN|merrem|Merrem|MERREM|meronem|Meronem|MERONEM|invanz|Invanz|INVANZ|doribax|Doribax|DORIBAX|vabomere|Vabomere|VABOMERE|recarbrio|Recarbrio|RECABRIO"
#setwd("C:/Users/aomura/Desktop/ricu2/mimic4/prescriptions.csv")
#PRES <- read.csv("prescriptions.csv")
#m4_penem_names_subIDs <- PRES[grep(penem_names, PRES$drug, ignore.case=TRUE),] %>% .$subject_id %>% unique()

##### Next, extract penem_associated ID data from chartevent.csv, poe.csv, labevents.csv.
#library(readr)
#setwd("C:/Users/aomura/Desktop/ricu2/mimic4/labevents.csv")
#results <- list()
#callback <- function(df, pos) {
#  filtered <- df %>% filter(subject_id %in% m4_penem_names_subIDs)
#  if (nrow(filtered) > 0) {
#    results[[length(results) + 1]] <<- filtered
#  }}

#read_csv_chunked(
#  file = "labevents.csv",
#  callback = SideEffectChunkCallback$new(callback),
#  chunk_size = 1e6  # 100万行ごとに読み込む
#)
#final_df <- bind_rows(results)

##### Save as csv, compress to csv.gz
#library(R.utils)
#setwd("C:/Users/aomura/Desktop/ricu2/miiv/icu")
#write.csv(final_df, "labevents2.csv") 
#gzip(filename = "labevents2.csv", destname = "labevents.csv.gz", remove = F)

##### Then, import each file with above code
```

#### 1 data management 

```{r M4 data arrange, warning=F, message=F}
###Attach mimic4 data (then you can check by ricu::src_data_avail())
Sys.setenv(RICU_DATA_PATH="C:\\Users\\aomura\\Desktop\\ricu2") 
dir5<-paste0(ricu::data_dir(),"\\miiv")
ricu::attach_src("miiv", data_dir = dir5, assign_env = NULL) #ricu::src_data_avail()

##### First, get penems pts in hadms
penem_names <- "penem|PENEM|primaxin|Primaxin|PRIMAXIN|merrem|Merrem|MERREM|meronem|Meronem|MERONEM|invanz|Invanz|INVANZ|doribax|Doribax|DORIBAX|vabomere|Vabomere|VABOMERE|recarbrio|Recarbrio|RECABRIO"

m4_received_carbapenems <- ricu::miiv$prescriptions[grep(penem_names, ricu::miiv$prescriptions$drug, ignore.case=TRUE),]
m4_received_carbapenems$drug_type <- ifelse(grepl("Imi", m4_received_carbapenems$drug)==T, "IMI", "non_IMI")
m4_received_carbapenems$drug_name <- ifelse(grepl("Mero", m4_received_carbapenems$drug)==T, "Meropenem", 
                                      ifelse(grepl("rtape", m4_received_carbapenems$drug)==T, "Ertapenem", 
                                       ifelse(grepl("Dori", m4_received_carbapenems$drug)==T, "Doripenem",
                                        ifelse(grepl("elebactam", m4_received_carbapenems$drug)==T, "Recabrio", 
                                         ifelse(grepl("ilastatin", m4_received_carbapenems$drug)==T, "Imipenem/Cilastatin", NA))))) 

##### Since miiv doesn't have icustay_id in prescription data, combine icustay data, then only keep icu-penem data
m4_icu_carbapenems <- m4_received_carbapenems %>% left_join(ricu::miiv$icustays %>% as.data.frame() %>% dplyr::select(hadm_id, stay_id, intime, outtime) %>% rename("ICU_intime"=intime, "ICU_outtime"=outtime), by="hadm_id") %>% filter(!is.na(ICU_intime) & ICU_intime<starttime & ICU_outtime >starttime)

#### Check ICU-penems
m4_icu_carbapenems %>% group_by(drug_type) %>% reframe(Subjects_Receiving=n_distinct(subject_id), Unique_hadm_admissions=n_distinct(hadm_id)) %>% rbind(c("","total",sum(.$Unique_hadm_admissions)),.)

#### Get 1st penem in the same hadm and the same ICUstay. Then, combine and remove continuous penem use before ICU transfer
m4_icu_1st_penems <- m4_icu_carbapenems %>% group_by(stay_id) %>% filter(starttime==min(starttime)) %>% rename("ICU_1st_penem_time"=starttime)
m4_hadm_1st_penems <- m4_received_carbapenems %>% group_by(hadm_id) %>% filter(starttime==min(starttime)) %>% rename("hadm_1st_penem_time"=starttime)

m4_icu_1st_penems_summary <- m4_icu_1st_penems %>% left_join(m4_hadm_1st_penems %>% dplyr::select(hadm_id, hadm_1st_penem_time), by="hadm_id") %>% filter(!(ICU_1st_penem_time > hadm_1st_penem_time))

#### Check ICU-penems
m4_icu_1st_penems_summary %>% group_by(drug_type, drug_name) %>% reframe(Subjects=n_distinct(subject_id), Unique_hadm=n_distinct(hadm_id)) %>% rbind(c("","penems before ICU removed","",sum(.$Unique_hadm)),.)

#Check/remove 1. duplicated pts to the both groups and 2. duplicated prescriptions in the same group
both_group_duplicated_hadm_id <-
m4_icu_1st_penems_summary %>% subset(drug_type=="IMI") %>% .[(m4_icu_1st_penems_summary %>% subset(drug_type=="IMI") %>% .$hadm_id) %in% (m4_icu_1st_penems_summary %>% subset(drug_type=="non_IMI") %>% .$hadm_id),] %>% .$hadm_id

m4_icu_1st_penems_summary2 <-
m4_icu_1st_penems_summary %>% subset(!(hadm_id %in% both_group_duplicated_hadm_id)) %>% group_by(hadm_id) %>% subset(!duplicated(hadm_id))

#### Check ICU-penems
m4_icu_1st_penems_summary2 %>% group_by(drug_type, drug_name) %>% reframe(dup_rm_subjects=n_distinct(subject_id), dup_rm_Unique_hadm=n_distinct(hadm_id)) %>% rbind(c("","after duplication removal","",sum(.$dup_rm_Unique_hadm)),.)

#### Check whether duplicated hadm_id was removed
#m4_icu_1st_penems_summary2$hadm_id %>% unique() %>% length() == m4_icu_1st_penems_summary2 %>% nrow()

#Summary of penems infusion time (What o'clock?)
ggplot(m4_icu_1st_penems_summary2, aes(ICU_1st_penem_time %>% substr(12,13) %>% as.numeric()))+geom_histogram()+ggtitle("penems infusion o'clock")+annotate("text", x = 2, y = 250, label=m4_icu_1st_penems_summary2$ICU_1st_penem_time %>% substr(12,13) %>% as.numeric() %>% mean(na.rm=T) %>% round(digits=1) %>% paste0("mean=",.))+annotate("text", x = 2, y = 230, label=m4_icu_1st_penems_summary2$ICU_1st_penem_time %>% substr(12,13) %>% as.numeric() %>% median(na.rm=T) %>% round(digits=1) %>% paste0("median=",.))

#put hours from ICU admit to 1stabx
m4_icu_1st_penems_summary2$time_ICUadmit_to_abx <- difftime(m4_icu_1st_penems_summary2$ICU_1st_penem_time, m4_icu_1st_penems_summary2$ICU_intime, units = "hours")

m4_icu_1st_penems_summary2b <- m4_icu_1st_penems_summary2 %>% subset(drug!= "Meropenem Desensitization")

list(
  c("N w/o duplication", m4_icu_1st_penems_summary2$hadm_id %>% unique() %>% length()),
  c("N w/o desensitization", m4_icu_1st_penems_summary2b %>% subset(drug!= "Meropenem Desensitization") %>% .$hadm_id %>% unique() %>% length()))
```
#### group transfer
```{r group transfer, message=F, warning=F}
m4_icu_carbapenems$drug_type %>% unique()

m4_first_IMI <- m4_icu_carbapenems %>% filter(drug_type=="IMI") %>% group_by(hadm_id) %>%
                filter(starttime==min(starttime)) %>% 
                rename("hadm_1st_time_IMI"=starttime) %>% 
                filter(hadm_id %in% m4_icu_1st_penems_summary2b$hadm_id) %>% distinct() %>% 
                dplyr::select(hadm_id, hadm_1st_time_IMI) 

m4_first_nonIMI <- m4_icu_carbapenems %>% filter(drug_type=="non_IMI") %>% group_by(hadm_id) %>%
                filter(starttime==min(starttime)) %>% 
                rename("hadm_1st_time_nIMI"=starttime) %>% 
                filter(hadm_id %in% m4_icu_1st_penems_summary2b$hadm_id) %>% distinct() %>% 
                dplyr::select(hadm_id, hadm_1st_time_nIMI) 

m4_icu_1st_penems_summary2c <- m4_icu_1st_penems_summary2b %>% left_join(m4_first_IMI, by="hadm_id") %>% left_join(m4_first_nonIMI, by="hadm_id") %>% distinct()

m4_icu_1st_penems_summary2c$time_switch_group0 <- 
  difftime(m4_icu_1st_penems_summary2c$hadm_1st_time_nIMI, 
                  m4_icu_1st_penems_summary2c$hadm_1st_time_IMI) %>% as.numeric() %>% abs()

m4_icu_1st_penems_summary2c$time_switch_group <- 
  ifelse(is.na(m4_icu_1st_penems_summary2c$time_switch_group0), 168, 
    ifelse(m4_icu_1st_penems_summary2c$time_switch_group0>168, 168, m4_icu_1st_penems_summary2c$time_switch_group0))

m4_icu_1st_penems_summary2d <- m4_icu_1st_penems_summary2c %>% filter(time_switch_group>24)
c("after group transfer within 24h removed",m4_icu_1st_penems_summary2d$hadm_id %>% unique() %>% length())
```

#### 2 crea data for pts exclusion

```{r M4 crea, warning=F, message=F}
#Get crea data. Put master data
m4_crea <- ricu::miiv$labevents %>% subset(itemid==50912 & hadm_id %in% m4_icu_carbapenems$hadm_id) %>% dplyr::select(hadm_id, charttime, valuenum) %>% rename("crea"=valuenum, "crea_time"=charttime)
m4_crea2 <- m4_crea %>% left_join(m4_icu_1st_penems_summary2d %>% dplyr::select(hadm_id, drug_type, ICU_1st_penem_time, time_ICUadmit_to_abx, time_switch_group), by="hadm_id")

#calculate time from 1st-penem to crea
m4_crea2$time_1stabx_to_crea <- difftime(m4_crea2$crea_time, m4_crea2$ICU_1st_penem_time, units = "hours")
m4_crea3 <- m4_crea2 %>% subset(time_1stabx_to_crea> -168.1 & time_1stabx_to_crea <168.1 & time_1stabx_to_crea<time_switch_group) #erase crea after group switch
m4_crea3_bef <- m4_crea3 %>% subset(time_1stabx_to_crea <0)
m4_crea3_after <- m4_crea3 %>% subset(time_1stabx_to_crea >0)

#Only keep pts at master DF with before/after crea
m4_icu_1st_penems_summary3 <- m4_icu_1st_penems_summary2d %>% subset(hadm_id %in% m4_crea3_bef$hadm_id & hadm_id %in% m4_crea3_after$hadm_id)

#check pts again
m4_icu_1st_penems_summary3 %>% group_by(drug_type) %>% reframe('Sub_w/_bef/after_crea'=n_distinct(subject_id), 'Hadm_w/_bef/after_crea'=n_distinct(hadm_id)) %>% rbind(c("","w/ crea patients", sum(.$'Hadm_w/_bef/after_crea')),.)
```

```{r m4 base and outcome creatinine assessment, warning=F, message=F}
#Get base_crea <- min crea between -7d to 0d for 1st-penem
#m4_crea3_bef & _after already limited > -168 or <168
m4_base_crea <- m4_crea3_bef %>% group_by(hadm_id) %>% filter(crea==min(crea)) %>% distinct() %>% dplyr::select(hadm_id, crea, time_1stabx_to_crea)

#Get near_crea <- nearest crea to 1st_penem before 1st_penem
m4_near_crea <- m4_crea3_bef %>% group_by(hadm_id) %>% filter(time_1stabx_to_crea==max(time_1stabx_to_crea)) %>% distinct() %>% dplyr::select(hadm_id, crea, time_1stabx_to_crea)

#Put those base and near crea data to crea_DF
m4_crea4 <- m4_crea3 %>% 
  left_join(m4_base_crea %>% rename("base_crea"=crea, "time_abx_to_basecrea"= time_1stabx_to_crea), by="hadm_id") %>% 
  left_join(m4_near_crea %>% rename("near_crea"=crea, "time_abx_to_nearcrea"= time_1stabx_to_crea), by="hadm_id") %>% 
  distinct ()

#Calculate base_KDIGO based on crea
m4_crea4$crea_ratio_near_by_base <- m4_crea4$near_crea/m4_crea4$base_crea
m4_crea4$base_KDIGO_crea_ratio <-  ifelse(m4_crea4$near_crea>4, 3, 
                                      ifelse(m4_crea4$crea_ratio_near_by_base>2.99, 3,
                                       ifelse(m4_crea4$crea_ratio_near_by_base>1.99, 2, 
                                        ifelse(m4_crea4$crea_ratio_near_by_base>1.49, 1, 0))))
m4_crea4$crea_diff_near_with_base <- m4_crea4$near_crea - m4_crea4$base_crea
m4_crea4$base_KDIGO_crea_diff <-  ifelse(m4_crea4$time_abx_to_nearcrea< -48.1, NA,
                                     ifelse(m4_crea4$time_abx_to_nearcrea> 0, NA, 
                                      ifelse(m4_crea4$crea_diff_near_with_base>0.29, 1, 0)))

m4_crea4$base_KDIGO_crea <- pmax(m4_crea4$base_KDIGO_crea_ratio, m4_crea4$base_KDIGO_crea_diff, na.rm=T)

m4_base_KDIGO_crea_summary <- m4_crea4 %>% group_by(hadm_id, base_crea, near_crea) %>% summarize("base_KDIGO_crea" = max(base_KDIGO_crea, na.rm = T)) %>% distinct()


#Calculate outcome_KDIGO based on crea
m4_crea4$ratio_to_basecrea <- m4_crea4$crea/m4_crea4$base_crea
m4_crea4$outcome_ratio_to_basecrea <- ifelse(as.numeric(m4_crea4$time_1stabx_to_crea)<0, NA, m4_crea4$ratio_to_basecrea)

m4_crea4$diff_to_basecrea <- m4_crea4$crea - m4_crea4$base_crea
m4_crea4$outcome_diff_to_basecrea <- ifelse(as.numeric(m4_crea4$time_1stabx_to_crea)<0, NA, m4_crea4$diff_to_basecrea)

m4_crea4$outcome_KDIGO_crea_ratio <- ifelse(m4_crea4$time_1stabx_to_crea<0, NA, 
                                     ifelse(m4_crea4$crea>4, 3, 
                                      ifelse(m4_crea4$ratio_to_basecrea>2.99, 3,
                                       ifelse(m4_crea4$ratio_to_basecrea>1.99, 2,
                                        ifelse(m4_crea4$ratio_to_basecrea>1.49, 1, 0)))))
m4_crea4$outcome_KDIGO_crea48 <-  ifelse(m4_crea4$time_1stabx_to_crea<0, NA, 
                                     ifelse(m4_crea4$time_1stabx_to_crea>48, NA, 
                                     ifelse(m4_crea4$crea>4, 3, 
                                      ifelse(m4_crea4$diff_to_basecrea>0.3, 1, 0))))
m4_crea4$outcome_KDIGO_crea <- pmax(m4_crea4$outcome_KDIGO_crea_ratio, m4_crea4$outcome_KDIGO_crea48, na.rm = T)

m4_outcome_KDIGO_crea_summary <- m4_crea4 %>% group_by(hadm_id, near_crea, base_crea) %>% 
  summarize("outcome_KDIGO_crea" = max(outcome_KDIGO_crea, na.rm=T), 
            "outcome_max_crea_diff" = max(outcome_diff_to_basecrea, na.rm=T), 
            "outcome_max_crea_ratio" = max(outcome_ratio_to_basecrea, na.rm=T),
            "base_KDIGO_crea" = max(base_KDIGO_crea, na.rm=T)) %>% distinct() %>% subset(!is.na(near_crea) & !is.infinite(outcome_max_crea_ratio))
#m4_outcome_KDIGO_crea_summary$base_KDIGO_crea
```


#### 3 base data collection

```{r M4 age and sex, warning=F, message=F}
m4_age <- ricu::load_concepts("age", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_age$age_group <- ifelse(m4_age$age<18, NA,
                        ifelse(m4_age$age<40, "18-39",
                         ifelse(m4_age$age<50, "40-49",
                          ifelse(m4_age$age<60, "50-59",
                           ifelse(m4_age$age<70, "60-69",
                            ifelse(m4_age$age<80, "70-79", "80+"))))))
m4_age$age_cat <- ifelse(m4_age$age_group=="18-39", 30, 
                   ifelse(m4_age$age_group=="40-49", 45,
                    ifelse(m4_age$age_group=="50-59", 55,
                     ifelse(m4_age$age_group=="60-69", 65,
                      ifelse(m4_age$age_group=="70-79", 75,
                      ifelse(m4_age$age_group=="80+", 85, NA))))))
m4_sex <- ricu::load_concepts("sex", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_bmi <- ricu::load_concepts("bmi", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_deptype <- ricu::load_concepts("adm", "miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id) %>% mutate("dep_type"=adm)
```


#### 4 past history

```{r ICD10, warning=F, message=F}
icd910_df <- data.frame(ricu::load_id(ricu::miiv$diagnoses_icd)) %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_icd9_df <- icd910_df %>% filter(icd_version==9)

#chronic heart failure
chf_codes<-c("39891","40201","40211","40291","40401","40403","40411","40413","40491","40493")
chf_codes3<-c("428") #Broad "heart failre"
chf_codes4<-c("4254","4255","4257","4258","4259")
m4_icd9_df <- m4_icd9_df %>% mutate(chf=ifelse(icd_code %in% chf_codes, TRUE, FALSE))
m4_icd9_df <- m4_icd9_df %>% mutate(chf=ifelse(str_sub(icd_code,1,3) %in% chf_codes3, TRUE, chf))
m4_icd9_df <- m4_icd9_df %>% mutate(chf=ifelse(str_sub(icd_code,1,4) %in% chf_codes4, TRUE, chf))

#DM (manually collected)
dm_codes <- c("24900","24901","24910","24911","24920","24921","24930","24931","24940","24941","24950","24951","24960","24961","24970","24971","24980","24981","24990","24991","25000","25001","25002","25003","25010","25011","25012","25013","25020","25021","25022","25023","25030","25031","25032","25033","25040","25041","25042","25043","25050","25051","25052","25053","25060","25061","25062","25063","25070","25071","25072","25073","25080","25081","25082","25083","25090","25091","25092","25093","2535","3572","36201","36202","36203","36204","36205","36206","36207","36641","5881","7751")
m4_icd9_df <- m4_icd9_df %>% mutate(dm=ifelse(icd_code %in% dm_codes, TRUE, FALSE))

#CKD
ckd_codes <- c('28521','40301','40311','40391','40402','40403','40412','40413','40492','40493')
ckd_codes3 <- c('585','586', '587')
ckd_codes4 <- c('5880','V420','V451', '5889', '7944')
m4_icd9_df<- m4_icd9_df %>% mutate(ckd=ifelse(icd_code %in% ckd_codes, TRUE, FALSE))
m4_icd9_df<- m4_icd9_df %>% mutate(ckd=ifelse(str_sub(icd_code,1,3) %in% ckd_codes3, TRUE, ckd))
m4_icd9_df<- m4_icd9_df %>% mutate(ckd=ifelse(str_sub(icd_code,1,4) %in% ckd_codes4, TRUE, ckd))

#hypertension
htn_codes <- c()
htn_codes3 <- c("401","402","403","404","405")
htn_codes4 <- c()
m4_icd9_df <- m4_icd9_df%>%mutate(htn=ifelse(icd_code%in%htn_codes,TRUE,FALSE))
m4_icd9_df <- m4_icd9_df%>% mutate(htn=ifelse(str_sub(icd_code,1,3) %in% htn_codes3, TRUE, FALSE))
m4_icd9_df <- m4_icd9_df%>%mutate(htn=ifelse(str_sub(icd_code,1,4)%in%htn_codes4,TRUE,htn))

###combine
#icd9_df <- icd9_df %>% group_by(icustay_id) %>% summarize(ph_htn=(sum(htn)>0), ph_dm=(sum(dm)>0), ph_chf=(sum(chf)>0), ph_ckd=(sum(ckd)>0))


m4_icd10_df <- icd910_df %>% filter(icd_version==10)
#icd10_list <- openxlsx::read.xlsx("section111_valid_icd10_october2025.xlsx") %>% dplyr::select(-'NF.EXCL')
#colnames(icd10_list) <- c("CODE", "s_desc", "l_desc")
#https://www.cms.gov/icd10m/FY2024-version41-fullcode-cms/fullcode_cms/P0150.html
#icd10_list[grep("hypertens", icd10_list$l_desc),] %>% distinct(CODE, s_desc, l_desc) %>% arrange(CODE)
#m4_icd10_df %>% arrange(icd_code) %>% .[7500:11000,]

icd10_dm_codes <- c("E08","E09","E10","E11","E12","E13") %>% paste(collapse = "|")
icd10_htn_codes <- c("I10","I119","I150","I151","I152","I158","I159","I160","I161","I169","I1A0") %>% paste(collapse = "|")
icd10_chf_codes <- c("I5042","I5043","I50812","I50813") %>% paste(collapse = "|")
icd10_ckd_codes <- c("I120","I129","I1310","I1311","N181","N182","N1830","N1831","N1832","N184","N185","N189") %>% paste(collapse = "|")

m4_icd10_df <- m4_icd10_df %>% mutate(dm=str_detect(icd_code, icd10_dm_codes),
                                      htn=str_detect(icd_code, icd10_htn_codes),
                                      chf=str_detect(icd_code, icd10_chf_codes),
                                      ckd=str_detect(icd_code, icd10_ckd_codes))

m4_icd910_comb <- rbind(m4_icd9_df %>% dplyr::select(stay_id, chf, dm, ckd, htn),
                        m4_icd10_df %>% dplyr::select(stay_id, chf, dm, ckd, htn)) %>% 
  group_by(stay_id) %>% summarize(ph_htn=(sum(htn)>0), ph_dm=(sum(dm)>0), ph_chf=(sum(chf)>0), ph_ckd=(sum(ckd)>0))
```

\_\_

#### **4 miiv dialysis data **

\_\_

```{r m4 dial, warning=F}
#check dialysis names
###Next, cellct dialysis event from d_items and output events.
###check ids for dialysis
m4_CRRT1_item_labels <- grep("CVV", ricu::miiv$d_items$label, value=TRUE)
m4_CRRT2_item_labels <- grep("CRR", ricu::miiv$d_items$label, value=TRUE)
m4_CRRT3_item_labels <- grep("Dialys",ricu::miiv$d_items$label, value=TRUE)

m4_RRTlabels <- c(m4_CRRT1_item_labels, m4_CRRT2_item_labels, m4_CRRT3_item_labels)
m4_RRTids <- ricu::miiv$d_items$itemid[ricu::miiv$d_items$label %in% m4_RRTlabels]
m4_RRTlabel <- ricu::miiv$d_items$label[ricu::miiv$d_items$itemid %in% m4_RRTids]
m4_d_RRTitems0 <- data.frame(item=m4_RRTids, label=m4_RRTlabel)

m4_d_RRTitems0$label %>% unique()

m4_RRT_omits <- c("Dialysis Access Site", "Dialysis Site Appearance", "Dialysis Catheter", "Dialysis patient", "Dialysis Catheter Cap Change", "Dialysis Catheter Change over Wire Date", "Dialysis Catheter Dressing Change", "Dialysis Catheter Insertion Date", "Dialysis Catheter Site Appear", "Dialysis CatheterTubing Change", "CRRT Filter Change", "Dialysis Catheter Tip Cultured", "Dialysis Catheter Discontinued", "Dialysis Catheter Dressing Type", "Dwell Time", "Peritoneal Dialysis Fluid Appearance", "Medication Added #1 (Peritoneal Dialysis)", "Solution", "Dialysis Access Type", "Reason for CRRT Filter Change", "Medication Added Amount  #1 (Peritoneal Dialysis)", "Medication Added", "Peritoneal Dialysis Catheter Type", "Peritoneal Dialysis Catheter Status", "Dialysis Catheter placed in outside facility", "Dialysis Catheter Type", "Dialysis Catheter Dressing Occlusive", "Calcium Gluconate (CRRT)", "KCl", "Medication Added #2 (Peritoneal Dialysis)" , "Medication Added Amount  #2 (Peritoneal Dialysis)", "Medication Added Units #2 (Peritoneal Dialysis)", "Dialysis Catheter Placement Confirmed by X-ray", "Dialysis/Pheresis Biopatch", "Heparin Sodium", "CRRT - Filter Type", "Calcium Gluconate")

m4_z <- paste(m4_RRT_omits, collapse="|")
m4_d_RRTitems <- m4_d_RRTitems0 %>% filter(!str_detect(label, m4_z))
#m4_d_RRTitems$label %>% unique()
```

```{r M4 base dialysis 1}
###Collect dialysis data.
###check dialysis from -7d to 1st_ABX
###With hadm to 1st_ABX time frame assessment, those are defined as KDIGO3 at 1st_ABX and excluded from primary outcome analysis. 
m4_dial_chartevents <- ricu::load_src(ricu::miiv$chartevents, itemid %in% m4_d_RRTitems$item) %>% dplyr::select(hadm_id, charttime, itemid) 
m4_dial_output <- ricu::miiv$outputevents %>% as.data.frame() %>% filter(itemid %in% m4_d_RRTitems$item) %>% dplyr::select(hadm_id, charttime, itemid) 
m4_dial_data <- rbind(m4_dial_chartevents, m4_dial_output) %>% subset(hadm_id %in% m4_icu_1st_penems_summary3$hadm_id) %>% 
              left_join(m4_d_RRTitems, by=c("itemid"="item")) %>% distinct()
m4_dial_data_b <- m4_dial_data %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(hadm_id, hadm_1st_penem_time, time_switch_group), by="hadm_id")
m4_dial_data_b$time_1stabx_to_dial <- difftime(m4_dial_data_b$charttime, m4_dial_data_b$hadm_1st_penem_time, units = "hours")

#erase event after group switch
#Take 1st RRT event
m4_dial_data_1st <- m4_dial_data_b %>% subset(time_1stabx_to_dial> -168.1 & time_1stabx_to_dial<168.1 & time_1stabx_to_dial < time_switch_group) %>% 
                    group_by(hadm_id) %>% filter(time_1stabx_to_dial==min(time_1stabx_to_dial)) %>% dplyr::select(hadm_id, time_1stabx_to_dial)


#combine to KDIGO summary data, and calculate KDIGO again with HD data
m4_outcome_KDIGO_crea_summary2 <- m4_outcome_KDIGO_crea_summary %>% left_join(m4_dial_data_1st, by="hadm_id") %>% distinct()
m4_outcome_KDIGO_crea_summary2$base_KDIGO_dial <- ifelse(is.na(m4_outcome_KDIGO_crea_summary2$time_1stabx_to_dial), 0,
                                                   ifelse(m4_outcome_KDIGO_crea_summary2$time_1stabx_to_dial<0, 3, 0))

m4_outcome_KDIGO_crea_summary2$base_KDIGO <- ifelse(m4_outcome_KDIGO_crea_summary2$base_KDIGO_dial > 0.1, 3,  m4_outcome_KDIGO_crea_summary2$base_KDIGO_crea)

m4_outcome_KDIGO_crea_summary2$outcome_new_dial <- ifelse(is.na(m4_outcome_KDIGO_crea_summary2$time_1stabx_to_dial), F, 
                                                    ifelse(m4_outcome_KDIGO_crea_summary2$time_1stabx_to_dial<0, NA, 
                                                     ifelse(m4_outcome_KDIGO_crea_summary2$time_1stabx_to_dial<168, T,  F)))

m4_outcome_KDIGO_crea_summary2$outcome_KDIGO_dial <- ifelse(is.na(m4_outcome_KDIGO_crea_summary2$outcome_new_dial), 0, 
                                                      ifelse(m4_outcome_KDIGO_crea_summary2$outcome_new_dial==F, 0, 3))

m4_outcome_KDIGO_crea_summary2$outcome_KDIGO <- pmax(m4_outcome_KDIGO_crea_summary2$outcome_KDIGO_crea, m4_outcome_KDIGO_crea_summary2$outcome_KDIGO_dial, na.rm = T)
  
m4_outcome_KDIGO_crea_summary2$outcome_KDIGO_inc <- ifelse(m4_outcome_KDIGO_crea_summary2$base_KDIGO==3, NA, ifelse(m4_outcome_KDIGO_crea_summary2$outcome_KDIGO > m4_outcome_KDIGO_crea_summary2$base_KDIGO, T, F))

#check outcome_KDIGO_inc
m4_outcome_KDIGO_crea_summary2$base_KDIGO %>% summary()
```

\_\_


#### 5 collect sofa
```{r M4 sofa, warning=F, message=F}
m4_ICU_intime_summary <- ricu::load_src(ricu::miiv$icustays) %>% filter(!is.na(stay_id)) %>% group_by(stay_id) %>% summarize("ICU_intime"=min(intime))

#m4_sofa <- ricu::load_concepts("sofa", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
#saveRDS(m4_sofa, "m4_sofa.rds")
m4_sofa <- readRDS("m4_sofa.rds") %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% mutate("sofa_time"=ICU_intime+charttime)

###Calculate the time from ICU_admission to 1st_ABX. Add those data in SOFA_DF
#carbapenem_d$time_ICUadmit_to_abx_days <- difftime(carbapenem_d$hadm_first_carbapenem_start, carbapenem_d$ICU_admit_time, units="days") #overwrite
m4_sofa_a <- m4_sofa %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% filter(!is.na(ICU_1st_penem_time)) %>% mutate("time_abx_to_sofa"= (sofa_time-ICU_1st_penem_time) %>% as.numeric(units="hours")) %>% distinct()

###Collect the SOFA scores which were closest to 1st-ABX time in each subjects
m4_sofa_b <- m4_sofa_a %>% subset(time_abx_to_sofa> -168.1 & time_abx_to_sofa < 0.01) %>% group_by(hadm_id) %>% slice_max(order_by = time_abx_to_sofa) %>% as.data.frame()

#m4_sofa_cns <- ricu::load_concepts("sofa_cns", src="miiv") %>% as.data.frame() 
#saveRDS(m4_sofa_cns,"m4_sofa_cns.rds")
m4_sofa_cns <- readRDS("m4_sofa_cns.rds") %>% as.data.frame() %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id) 
m4_sofa_cns2 <- m4_sofa_cns %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(stay_id, time_ICUadmit_to_abx), by="stay_id") %>% filter(!is.na(time_ICUadmit_to_abx)) %>% distinct()
m4_sofa_cns2$proximality_to_abx <- m4_sofa_cns2$charttime - m4_sofa_cns2$time_ICUadmit_to_abx
m4_sofa_cns3 <- m4_sofa_cns2 %>% subset(proximality_to_abx>-168.1 & proximality_to_abx<0.01) %>% group_by(stay_id) %>% slice_max(order_by = proximality_to_abx)

#m4_sofa_renal <- ricu::load_concepts("sofa_renal", src="miiv") %>% as.data.frame()
#saveRDS(m4_sofa_renal,"m4_sofa_renal.rds")
m4_sofa_renal <- readRDS("m4_sofa_renal.rds") %>% as.data.frame() %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_sofa_renal2 <- m4_sofa_renal %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(stay_id, time_ICUadmit_to_abx), by="stay_id") %>% filter(!is.na(time_ICUadmit_to_abx)) %>% distinct()
m4_sofa_renal2$proximality_to_abx <- m4_sofa_renal2$charttime - m4_sofa_renal2$time_ICUadmit_to_abx
m4_sofa_renal3 <- m4_sofa_renal2 %>% subset(proximality_to_abx>-168.1 & proximality_to_abx<0.01) %>% group_by(stay_id) %>% slice_max(order_by = proximality_to_abx) 

#m4_sep <- ricu::load_concepts("sep3", src="miiv") %>% as.data.frame()
#saveRDS(m4_sep,"m4_sep.rds")
m4_sep <- readRDS("m4_sep.rds") %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% mutate("sep_time"=ICU_intime+charttime) %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_sep2 <- m4_sep %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% filter(!is.na(ICU_1st_penem_time)) %>% distinct()
m4_sep2$proximality_to_abx <- (m4_sep2$sep_time - m4_sep2$ICU_1st_penem_time) %>% as.numeric(units="hours")
m4_sep3 <- m4_sep2 %>% subset(proximality_to_abx>-168.1 & proximality_to_abx<0.01) %>% group_by(hadm_id) %>% slice_max(order_by = proximality_to_abx)

#m4_sirs <- ricu::load_concepts("sirs", src="miiv") %>% as.data.frame()
#saveRDS(m4_sirs,"m4_sirs.rds")
m4_sirs <- readRDS("m4_sirs.rds") %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% mutate("sirs_time"=ICU_intime+charttime) %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_sirs2 <- m4_sirs %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% filter(!is.na(ICU_1st_penem_time)) %>% distinct()
m4_sirs2$proximality_to_abx <- (m4_sirs2$sirs_time - m4_sirs2$ICU_1st_penem_time) %>% as.numeric(units="hours")
m4_sirs3 <- m4_sirs2 %>% subset(proximality_to_abx>-168.1 & proximality_to_abx<0.01) %>% group_by(hadm_id) %>% slice_max(order_by = proximality_to_abx)

#m4_qsofa <- ricu::load_concepts("qsofa", src="miiv") %>% as.data.frame()
#saveRDS(m4_qsofa,"m4_qsofa.rds")
m4_qsofa <- readRDS("m4_qsofa.rds") %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% mutate("qsofa_time"=ICU_intime+charttime) %>% filter(stay_id %in% m4_icu_1st_penems_summary3$stay_id)
m4_qsofa2 <- m4_qsofa %>% left_join(m4_icu_1st_penems_summary3 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% filter(!is.na(ICU_1st_penem_time)) %>% distinct()
m4_qsofa2$proximality_to_abx <- (m4_qsofa2$qsofa_time - m4_qsofa2$ICU_1st_penem_time) %>% as.numeric(units="hours")
m4_qsofa3 <- m4_qsofa2 %>% subset(proximality_to_abx>-168.1 & proximality_to_abx<0.01) %>% group_by(hadm_id) %>% slice_max(order_by = proximality_to_abx)
```


```{r M4 KDIGO combine}
m4_icu_1st_penems_summary4 <- m4_icu_1st_penems_summary3 %>%  
  left_join(m4_outcome_KDIGO_crea_summary2, by="hadm_id") %>% 
  left_join(m4_age, by="stay_id") %>% left_join(m4_sex, by="stay_id") %>% left_join(m4_bmi, by="stay_id") %>% 
  left_join(m4_deptype, by="stay_id") %>% 
  left_join(m4_icd910_comb, by="stay_id") %>% 
  left_join(m4_sofa_b %>% dplyr::select(-ICU_1st_penem_time, -stay_id), by="hadm_id") %>% 
  left_join(m4_sofa_cns3 %>% dplyr::select(stay_id, sofa_cns), by="stay_id") %>% 
  left_join(m4_sofa_renal3 %>% dplyr::select(stay_id, sofa_renal), by="stay_id") %>% 
  left_join(m4_qsofa3 %>% dplyr::select(hadm_id, qsofa), by="hadm_id") %>% 
  left_join(m4_sirs3 %>% dplyr::select(hadm_id, sirs), by="hadm_id") %>% 
  left_join(m4_sep3 %>% dplyr::select(hadm_id, sep3), by="hadm_id") %>% 
  filter(!is.na(base_KDIGO)&!is.na(base_crea)) %>% distinct() %>% as.data.frame()

m4_icu_1st_penems_summary4$sofa_cns <- ifelse(is.na(m4_icu_1st_penems_summary4$sofa_cns), 0, m4_icu_1st_penems_summary4$sofa_cns) #30-40 sofa_cns are NA probably due to sedation (1 NA for sofa_renal->?). inpute 0
m4_icu_1st_penems_summary4$sofa_renal <- ifelse(is.na(m4_icu_1st_penems_summary4$sofa_renal), 0, m4_icu_1st_penems_summary4$sofa_renal) 
m4_icu_1st_penems_summary4$sofa_others0 <- m4_icu_1st_penems_summary4$sofa - m4_icu_1st_penems_summary4$sofa_cns - m4_icu_1st_penems_summary4$sofa_renal
m4_icu_1st_penems_summary4$sofa_others <- ifelse(m4_icu_1st_penems_summary4$sofa_others0<0, 0, m4_icu_1st_penems_summary4$sofa_others0)
#m4_icu_1st_penems_summary4 %>% dplyr::select(sofa, sofa_cns, sofa_renal, sofa_others) %>% summary()

m4_icu_1st_penems_summary4 %>% group_by(drug_type) %>% summarise("miiv4 final" = n())
```


####Get ohter outcome data using "load_concept"
```{r m4_other outcomes, message=F}
m4_death_DF0 <- ricu::load_concepts("death", src="miiv") %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% 
                left_join(m4_icu_1st_penems_summary4 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time, time_switch_group)) %>%
                filter(!is.na(ICU_1st_penem_time)) %>% 
                mutate("time_abx_to_death" = (index_var + ICU_intime - ICU_1st_penem_time) %>% as.numeric(units="hours"))
m4_death_DF <- m4_death_DF0 %>% subset(time_abx_to_death<168 & time_abx_to_death<time_switch_group)

m4_loshp_DF0 <- ricu::load_concepts("los_hosp", src="miiv")  %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% 
                   left_join(m4_icu_1st_penems_summary4 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time)) %>%
                   filter(!is.na(ICU_1st_penem_time)) %>% 
                   mutate("time_abx_to_loshp" = as.numeric(los_hosp*24, units="hours")+ as.numeric((ICU_intime - ICU_1st_penem_time), units="hours"))
m4_loshp_DF <- m4_loshp_DF0 %>% subset(time_abx_to_loshp<168)
#m4_los_icu_DF <- ricu::load_concepts("los_icu", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary4$stay_id) 



#add to master DF
m4_icu_1st_penems_summary5 <- m4_icu_1st_penems_summary4 %>% left_join(., m4_loshp_DF %>% dplyr::select(-ICU_1st_penem_time), by="hadm_id") %>% 
                                 left_join(., m4_death_DF %>% dplyr::select(hadm_id, stay_id, time_abx_to_death), by="hadm_id") %>% distinct()

m4_icu_1st_penems_summary5$death_in_hosp <- ifelse(is.na(m4_icu_1st_penems_summary5$time_abx_to_death), F, T)
m4_icu_1st_penems_summary5$death_in_7d <- ifelse(is.na(m4_icu_1st_penems_summary5$time_abx_to_death), F, 
                                                 ifelse(m4_icu_1st_penems_summary5$time_abx_to_death <168, T, F))
m4_icu_1st_penems_summary5$outcome_KDIGO_inc_or_death <- ifelse(is.na(m4_icu_1st_penems_summary5$outcome_KDIGO_inc), NA, 
                                                                      ifelse(m4_icu_1st_penems_summary5$outcome_KDIGO_inc==T, T,
                                                                             ifelse(m4_icu_1st_penems_summary5$death_in_7d==T,T, F)))


#cult_names <- "culture|CULTURE|Culture"
cult_names <- "BLOOD CULTURE"
non_cult_names <- "viral|VIRAL|Viral"

m4_cult<- ricu::miiv$microbiologyevents[grep(cult_names, ricu::miiv$microbiologyevents$spec_type_desc, ignore.case=TRUE),] %>% .[!grep(non_cult_names, .$spec_type_sesc)]%>% dplyr::select(hadm_id, charttime) %>% left_join(m4_icu_1st_penems_summary5 %>% dplyr::select(hadm_id, hadm_1st_penem_time), by="hadm_id") %>% filter(!is.na(hadm_1st_penem_time)) %>% mutate("time_cult_to_1stabx"=(charttime-hadm_1st_penem_time) %>% as.numeric()/3600) %>% filter(time_cult_to_1stabx> -72 & time_cult_to_1stabx<24) %>% mutate("pre_blood_culture"=T)

m4_icu_1st_penems_summary5 %>% filter(hadm_id %in% m4_cult$hadm_id) %>% group_by(drug_type) %>% reframe(dup_rm_subjects=n_distinct(subject_id), dup_rm_Unique_hadm=n_distinct(hadm_id))
m4_icu_1st_penems_summary6 <- m4_icu_1st_penems_summary5 %>% left_join(m4_cult %>% dplyr::select(hadm_id, pre_blood_culture)) %>% distinct()
m4_icu_1st_penems_summary6$pre_blood_culture <- ifelse(is.na(m4_icu_1st_penems_summary6$pre_blood_culture), F,
                                              ifelse(m4_icu_1st_penems_summary6$pre_blood_culture==F, F, T))
m4_icu_1st_penems_summary6$time_ICUadmit_to_abx <- m4_icu_1st_penems_summary6$time_ICUadmit_to_abx %>% as.numeric()
m4_icu_1st_penems_summary7 <- m4_icu_1st_penems_summary6 %>% mutate("icustay_id"=NA) 
```

```{r vancomycin}
van_names <- "vanco|firvanq|lyphocin"
m4_received_van <- ricu::miiv$prescriptions[grep(van_names, ricu::miiv$prescriptions$drug, ignore.case=TRUE),]
#m4_received_van$drug %>% unique()

m4_received_van2 <- left_join(m4_received_van %>% dplyr::select(hadm_id, starttime),
                              m4_icu_1st_penems_summary7 %>% dplyr::select(hadm_id, ICU_1st_penem_time), by="hadm_id") %>% na.omit() %>% 
  mutate("hour_van_to_abx"=(starttime-ICU_1st_penem_time)/3600 %>% as.numeric()) %>% filter(abs(hour_van_to_abx)<24) %>% mutate("treat_van"=T)

m4_icu_1st_penems_summary8 <- left_join(m4_icu_1st_penems_summary7, m4_received_van2 %>% dplyr::select(hadm_id, treat_van)) %>% distinct() %>% mutate("treat_van"=ifelse(is.na(treat_van), F, T))
```
```{r vaso, message=F}
m4_vaso <-
rbind(
ricu::load_concepts("adh_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2],
ricu::load_concepts("dobu_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2],
ricu::load_concepts("dopa_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2],
ricu::load_concepts("epi_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2],
ricu::load_concepts("norepi_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2],
ricu::load_concepts("phn_rate", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary8$stay_id) %>% .[,1:2])

m4_vaso2 <- m4_vaso %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% mutate("vaso_time"=starttime+ICU_intime)
m4_vaso3 <- m4_vaso2 %>% left_join(m4_icu_1st_penems_summary8 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% mutate("time_abx_to_vaso"=(vaso_time-ICU_1st_penem_time) %>% as.numeric(units="hours")) 
m4_vaso4 <- m4_vaso3 %>% filter(time_abx_to_vaso> -168 & time_abx_to_vaso<0) %>% group_by(hadm_id) %>% summarize("vasopressor"=min(time_abx_to_vaso))

m4_icu_1st_penems_summary9 <- m4_icu_1st_penems_summary8 %>% left_join(m4_vaso4, by="hadm_id") %>% distinct()
m4_icu_1st_penems_summary9$vasopressor <- ifelse(is.na(m4_icu_1st_penems_summary9$vasopressor), F, T)
```

```{r vent, message=F}
m4_vent <- rbind(
ricu::load_concepts("vent_ind", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary9$stay_id) %>% .[,1:3],
ricu::load_concepts("mech_vent", src="miiv") %>% filter(stay_id %in% m4_icu_1st_penems_summary9$stay_id) %>% .[,1:3]) %>%  mutate("dur_var2"=as.numeric(dur_var, units="hours"))
  
m4_vent2 <- m4_vent %>% left_join(m4_ICU_intime_summary, by="stay_id") %>% 
                  left_join(m4_icu_1st_penems_summary9 %>% dplyr::select(hadm_id, stay_id, ICU_1st_penem_time), by="stay_id") %>% 
                  mutate("time_abx_to_vent_start"=as.numeric(starttime+ICU_intime-ICU_1st_penem_time, unit="hours"),
                         "time_abx_to_vent_end"=dur_var2+time_abx_to_vent_start) %>% 
                  filter((time_abx_to_vent_start<0 & time_abx_to_vent_end>0)) %>% mutate(ventilation=T) %>% distinct()

m4_icu_1st_penems_summary10 <-  m4_icu_1st_penems_summary9 %>% left_join(m4_vent2 %>% dplyr::select(hadm_id, stay_id, ventilation), by="hadm_id") %>% distinct()
m4_icu_1st_penems_summary10$ventilation <- ifelse(is.na(m4_icu_1st_penems_summary10$ventilation), F, T)
```

```{r carbapenems count, message=F}
m4_carbapenems_counts <- 
m4_received_carbapenems %>% filter(drug!="Meropenem Desensitization"&drug!="Meropenem Graded Challenge"&drug!="Ertapenem Oral Solution"&drug!="Ertapenem Graded Challenge") %>% dplyr::select(hadm_id, drug_name, starttime) %>% 
  left_join(m4_icu_1st_penems_summary10 %>% dplyr::select(hadm_id, ICU_1st_penem_time), by="hadm_id") %>% 
  mutate("time_first_abx_to_abx"=difftime(starttime, ICU_1st_penem_time)/3600) %>% filter(time_first_abx_to_abx<168) %>% 
  group_by(hadm_id, drug_name) %>% summarise(n()) %>% pivot_wider(names_from = drug_name, values_from = "n()")

m4_carbapenems_counts[is.na(m4_carbapenems_counts)] <- 0

m4_icu_1st_penems_summary11 <- left_join(m4_icu_1st_penems_summary10, m4_carbapenems_counts, by="hadm_id") %>% rename("Imipenem/Cilastatin/Relebactam"="Recabrio")
```

```{r observation period, message=F}
m4_crea_ob_DF <- m4_crea2 %>% group_by(hadm_id) %>% summarize('last_crea'=max(time_1stabx_to_crea)) %>% na.omit()
m4_dial_ob_DF <- m4_dial_data_b %>% group_by(hadm_id) %>% summarize('last_dial'=max(time_1stabx_to_dial)) 

m4_obs_summary <- m4_crea_ob_DF %>% dplyr::select(hadm_id, last_crea) %>% 
                left_join(m4_dial_ob_DF %>% dplyr::select(hadm_id, last_dial), by="hadm_id") %>% 
                left_join(m4_death_DF0 %>% dplyr::select(hadm_id, time_abx_to_death), by="hadm_id") %>% 
                left_join(m4_loshp_DF0 %>% dplyr::select(hadm_id, time_abx_to_loshp), by="hadm_id") %>% 
                left_join(m4_icu_1st_penems_summary11 %>% dplyr::select(hadm_id, time_switch_group), by="hadm_id")

m4_obs_summary$obs_period0 <- pmax(m4_obs_summary$last_crea, m4_obs_summary$last_dial, m4_obs_summary$time_abx_to_death, m4_obs_summary$time_abx_to_loshp, na.rm = T)
m4_obs_summary$obs_period <- pmin(m4_obs_summary$obs_period0, m4_obs_summary$time_switch_group, 168, na.rm = T)
m4_icu_1st_penems_summary12 <- left_join(m4_icu_1st_penems_summary11, m4_obs_summary %>% dplyr::select(hadm_id, obs_period, time_abx_to_death, time_abx_to_loshp), by="hadm_id")

```

```{r save MIMIC4}
write.csv(m4_icu_1st_penems_summary12, "MDF_miiv.csv")
c("total",
read.csv("MDF_miiv.csv") %>% .$hadm_id %>% unique() %>% length(),
"base AKI <3",
read.csv("MDF_miiv.csv") %>% filter(base_KDIGO<2.9) %>% .$hadm_id %>% unique() %>% length())
```
